# Generated by Django 3.1.4 on 2021-03-04 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('instanceid', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.DecimalField(decimal_places=12, max_digits=13)),
                ('gender', models.DecimalField(decimal_places=12, max_digits=13)),
                ('race', models.DecimalField(decimal_places=12, max_digits=13)),
                ('income', models.DecimalField(decimal_places=12, max_digits=13)),
                ('age', models.DecimalField(decimal_places=12, max_digits=13)),
            ],
        ),
        migrations.CreateModel(
            name='Counterfactuals',
            fields=[
                ('Counterfactualid', models.AutoField(primary_key=True, serialize=False)),
                ('education', models.DecimalField(decimal_places=12, max_digits=13)),
                ('gender', models.DecimalField(decimal_places=12, max_digits=13)),
                ('race', models.DecimalField(decimal_places=12, max_digits=13)),
                ('income', models.DecimalField(decimal_places=12, max_digits=13)),
                ('age', models.DecimalField(decimal_places=12, max_digits=13)),
                ('unfair', models.BooleanField()),
                ('unactionable', models.BooleanField()),
                ('instanceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aifeedback.instances')),
            ],
        ),
    ]
