# Generated by Django 3.1.4 on 2021-03-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifeedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counterfactuals',
            name='unactionable',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='counterfactuals',
            name='unfair',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
