# Generated by Django 3.1.4 on 2021-03-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aifeedback', '0003_auto_20210308_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instances2',
            fields=[
                ('instanceid', models.AutoField(primary_key=True, serialize=False)),
                ('c_charge_degree', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('age', models.IntegerField()),
                ('priors_count', models.IntegerField()),
                ('recidivism', models.BooleanField()),
            ],
        ),
    ]
