# Generated by Django 3.1.4 on 2021-03-10 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aifeedback', '0005_counterfactuals2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='counterfactuals2',
            old_name='unfair',
            new_name='fair',
        ),
    ]
